#!/bin/bash

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 一 二 三 四 五 六 七 八 九 十

bspc config border_width         2
bspc config window_gap          10
bspc config focus_follows_pointer true

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

### Autostart
sxhkd &
xset r rate 185 75
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
~/.config/bspwm/nitrogen.sh
polybar -r bar1
picom --config ~/.config/picom/picom.conf
